### ISSUE TITLE
Problem with requiring React

### ISSUE THREAD

**Issue by Velover** [littensy/charm#3]
I started using Charm and during the first test I got an error

![image](https://github.com/littensy/charm/assets/64728790/969e26bd-c69d-4395-a3f6-b5dbdf02bce0)
![image](https://github.com/littensy/charm/assets/64728790/747e378d-231c-4eb5-b04b-a96788cb19ac)

Then i started digging in the error and i found that Charm doesnt Require React correctly

![image](https://github.com/littensy/charm/assets/64728790/460733bc-41ad-4a4b-a4fc-87288584bc42)
In the module there is a variable
```lua
local Package = script.Parent.Parent
```

and if you look at the hierarchy it leads to src
![image](https://github.com/littensy/charm/assets/64728790/20fba1d9-f67a-4519-b775-dc10ec3b486a)

therefore Package.Parent leads to the folder charm instead of @rbxts so it's unable to find React

after I manually added additional .Parent at the end it started working

**Comment by littensy** [comment]
Should be fixed in 0.2.1 👍
